### ISSUE TITLE
Typo on Second line

### ISSUE THREAD

**Issue by version0chiro** [codingmickey/codingmickey#1]
I think you meant to write a full stack developer and not a afull developer

**Comment by codingmickey** [comment]
Yes yes 😅 fixed it, hands work slower than the brain sometimes 😂

**Comment by version0chiro** [comment]
Get a mechanical keyboard, hands will go faster 🚀🚀🚀

**Comment by codingmickey** [comment]
Then too more typing practice needed 🤕 muscle memory build hone time lag raha hai currently 50-55 wpm hi hota hai 🥲
